---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  annotations:
    autoscaling.knative.dev/maxScale: "1"
    autoscaling.knative.dev/minScale: "1"
  labels:
    apps.tanzu.vmware.com/workload-type: web
  name: cvs-test
  namespace: dev
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/jmconelogin/spring-sql-jpa-cvs
